services:
  - type: web
    name: sanjorge-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && npm run seed:prod && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        sync: false
